[package]
org = "wso2"
name = "superapp_mobile_service"
version = "1.0.0"
distribution = "2201.10.4"

[build-options]
observabilityIncluded = true

dependency = [
	"ballerina/http:2.14.5",
	"ballerina/log:2.13.0",
	"ballerina/io:1.8.0"
]
