[package]
org = "lsf"
name = "backend_payslip_viewer"
version = "0.1.0"
distribution = "2201.12.9"

[build-options]
observabilityIncluded = true
<<<<<<< HEAD
=======
[[dependency]]
org = "ballerinax"
name = "sql"
version = "1.10.0"

[[dependency]]
org = "ballerinax"
name = "sqlite"
version = "1.10.0"
>>>>>>> 5b8687358412d7783d27a172e47e38deb9ccc564
