[package]
org = "lsf"
name = "backend_payslip_viewer"
version = "0.1.0"
distribution = "2201.12.9"

[build-options]
observabilityIncluded = true
[[dependency]]
org = "ballerinax"
name = "sql"
version = "1.10.0"

[[dependency]]
org = "ballerinax"
name = "sqlite"
version = "1.10.0"
